<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-07T18:50:57 IST" name="Default suite" finished-at="2023-09-07T18:52:28 IST" duration-ms="90697">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:Runner.TestApplication@72cc7e6f]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2023-09-07T18:50:57 IST" name="Default test" finished-at="2023-09-07T18:52:28 IST" duration-ms="90697">
      <class name="Runner.TestApplication">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:Runner.TestApplication@72cc7e6f]" started-at="2023-09-07T18:50:57 IST" name="setUpClass" finished-at="2023-09-07T18:50:58 IST" duration-ms="1051" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:Runner.TestApplication@72cc7e6f]" started-at="2023-09-07T18:50:58 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-09-07T18:52:11 IST" duration-ms="73118" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Creation of Identification Details record with valid data"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[To verify the Funcnality of AdditionalCustomerInfo]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Karthikeyan] but found [987456321023]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Karthikeyan] but found [987456321023]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdefinitions.AdditionalCustomerInfo_Steps.user_verify_the_same_record_got_saved_in_screen(AdditionalCustomerInfo_Steps.java:616)
at âœ½.user verify the same record got saved in screen(file:///C:/Users/inindc00606/git/KarthikeyanIjara/Ijara_Karthi2/src/test/java/features/Ijarah_AdditionalCustomerInfo.feature:32)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:Runner.TestApplication@72cc7e6f]" started-at="2023-09-07T18:52:11 IST" name="tearDownClass" finished-at="2023-09-07T18:52:28 IST" duration-ms="16485" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- Runner.TestApplication -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
